### ISSUE TITLE
Let default_field_resolver check "typing.Mapping" instead of the more restrictive "dict"

### ISSUE THREAD

**Issue by jstlaurent** [graphql-python/graphql-core#102]
# Feature requests

The current `default_field_resolver` checks against instances of `dict` specifically to decide whether to use `get` or `getattr` to access the field on the `source`. Checking against [typing.Mapping](https://docs.python.org/3.6/library/typing.html#typing.Mapping) would be more flexible, allowing, for example, a [ChainMap](https://docs.python.org/3/library/collections.html#collections.ChainMap) to be used as the underlying source.

**Comment by Cito** [comment]
Sounds like a good idea. But we need to explore these questions:
* Maybe we should check against `collections.abc.Mapping` instead? What are the pros/cons?
* Performance implications: A quick test showed that using `collections.abc.Mapping` is ~ 6x slower, `typing.Mapping` is ~ 14x slower than using `dict`. This may be problematic, since the checks happen so frequently.

**Comment by jstlaurent** [comment]
Those are very good questions. Thank you for testing the performance. I wonder if there is a good way to benchmark the impact on the whole process of resolving an object structure.

**Comment by Cito** [comment]
It is hardly measurable with our standard benchmarks and probably doesn't matter much in real life as well.

So I've implemented this now and added a test using ChainMap. I've used abc.collections.Mapping because typing.Mapping is intended to be used for type checking, not for runtime checks, and more or less only proxies the checks anyway.

Will be available in the next release.

**Comment by jstlaurent** [comment]
Thank you very much!
