### ISSUE TITLE
Performance of validate, in the context of graphql(_sync)

### ISSUE THREAD

**Issue by alexchamberlain** [graphql-python/graphql-core#116]
I've benchmarked a few of our use cases and up to 85% of the runtime is in `validation.validate`; as far as I can tell, there's been no discussion of this on Issues, so I thought I'd open an issue to see if this is a known issue?

I'll follow up with a PR that demonstrates the issue and has some improvements, but won't be production quality at this stage.

**Comment by Cito** [comment]
Hi @alexchamberlain. Not sure if we have explicitly discussed this already. One issue is always when and how to avoid the validation step and not validating the same query multiple times (#70 is related to that). 

I'm glad about PRs that try to improve performance. However, the code should not deviate too much from the original code in GraphQL.js since this will make it difficult to merge future change in GraphQL.js back here. If you want to introduce larger algorithmic changes, it may make more sense to suggest them on the GraphQL.js issue tracker, implement these in JavaScript and then merge back here.

**Comment by alexchamberlain** [comment]
Thanks @Cito 

I've opened #117 with the benchmark script I used. The main change is to memoise the lookup of visit functions, which is more of a Python optimisation I think?

**Comment by Cito** [comment]
Thanks. I will look into this if I find some time. Please note that there are already some benchmark scripts. It would make sense to add another benchmark that explicitly focuses on validation then.

**Comment by alexchamberlain** [comment]
Ah, sorry - I completely missed that! I can look to refactor my benchmarks there if you like?

**Comment by Cito** [comment]
Sorry for leaving this open for so long. I think it has now been addressed and solved in ac3caf60fe9f2dd2ef70bcd530ed0e0d0c54b638 and #150.
