### ISSUE TITLE
Support for AsyncIterable resolvers

### ISSUE THREAD

**Issue by Jamie-Chang** [graphql-python/graphql-core#123]
Currently async resolvers for arrays are async functions that return an iterable.

There seem to be a lack for support for resolvers that return an AsyncIterable. For example, using motor to query a mongo collection:
```
async def resolve_users(*_):
    async for document in collection.find({}):
        yield document
```
Of course, a work around would be to fetch all documents first, but supporting the async iterator / generator would be a much nicer way to do it.

**Comment by Cito** [comment]
Sorry for neglecting this issue for so long.

GraphQL-core already supports async iterables in the context of subscriptions. However, I assume the request is about list field resolvers for ordinary queries. This is currently not supported in GraphQL.js and GraphQL-core.

However, there is a PR that implements this feature in GraphQL.js in order to support the `@stream` directive (see [#2757](https://github.com/graphql/graphql-js/pull/2757) there). If this will be accepted, it will eventually also become available in GraphQL-core.

Until then, I will implement experimental support for async iterables in GraphQL-core already in the upcoming 3.2 release.
