### ISSUE TITLE
Rename project/repository

### ISSUE THREAD

**Issue by aryaniyaps** [graphql-python/graphql-core#139]
hey there! This is a wonderful repository, and a really great reference implementation!
Here's why I think that this repository should be renamed to `graphql` or `graphql-py` instead of `graphql-core`

The current name sort of gives us a feel that it's not for the end user.
It gives us a feel that this project is only for other graphql libraries to build abstractions on top of.

in the GraphQL ecosystem, you'd generally build out your whole schema with graphql-js, in fact it was the only way during the start. It was after the reference implementation that we got apollo server/ nexus.

in the Python ecosystem, this seems like the opposite - graphql-core is relatively newer than graphene and is receiving lesser adoption rates.

also, I think that it would also help renaming the PyPI project name to `graphql` instead of graphql-core`.
This is my opinion, what do you think?

**Comment by Cito** [comment]
Hi @codebyaryan and thanks for the feedback.

Regarding the impression that GraphQL-core is newer than Graphene, that's actually not the case. GraphQL-core had been created in 2016 by Syrus Akbari as a port of GraphQL.js and *then* he created Graphene as an (actually very thin) wrapper around it in order to make the API a bit more Pythonic and easy to use. He created several other libraries in the Graphene/GraphQL-Python ecosystem like the gql client which are also based on GraphQL-core. Later, alternative packages such as Strawberry were also based on GraphQL-core. The current version 3 of GraphQL-core is just a "reincarnation" of the legacy version 2, making use of Python 3 features and porting the latest changes and additions from GraphQL.js. So I think the name "GraphQL-core" still describes it's purpose very well, even though of course you can use it standalone and that might be sufficient for many purposes.

The number of existing libraries based on GraphQL-core is one reason why I don't think it would be a good idea to rename it. The move from version 2 to 3 was already a big enough disruption. Unfortunately, the GraphQL-Python ecosystem lacks maintainers, it's all based on voluntary work, Syrus is very busy with other projects, so we have difficulties to keep it going and finally release version 3 of Graphene and the other libraries based on GraphQL-core version 3. In this situation, I think it's better to keep the naming and [versioning](https://github.com/graphql-python/graphql-core/issues/139) scheme in order to avoid additional confusion and friction.
