### ISSUE TITLE
 Inquiry about the release of a stable version after 3.2.3

### ISSUE THREAD

**Issue by DeanNeaht** [graphql-python/graphql-core#224]
The last stable release of graphql-core was version 3.2.3, which was published in 2022. Since then, only alpha versions have been released. I would like to ask if there are any plans to release a new stable version based on the changes introduced in the alpha versions.

Is there any specific issue that is preventing the release of a stable version? If there's anything I can do to assist in resolving any blockers, please let me know.

**Comment by Cito** [comment]
Main reason is that I have very limited time to maintain this project and for me the priority was to port changes from the development branch of GraphQL.js (v17 which is also still alpha). I will try to port the latest changes from the stable branch (v 16) as well (it has some backports from v17) and create another release that officially supports newer Python versions after the summer break. If you have any particular problems with the current stable branch let me know so that I can address them.

**Comment by Cito** [comment]
Quick status update: I'm now working on the stable branch again, there will be a release soon.

**Comment by Cito** [comment]
Version 3.2.4 has been released now.

Unfortunately, forgot that the stable branch still has a setup.py in addition to pyproject.toml, and only updated the supported Python versions there. Therefore it is currently not listed as supporting Py 3.11 and 3.12 on PyPI though it does. Will create another stable version soon that also supports the upcoming Py 3.13 release.

**Comment by Cito** [comment]
Version 3.2.5 that supports Python 3.13 has been released now.
